package org.lq.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lq.pojo.Emp;
import org.lq.pojo.EmpExample;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    long countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Short empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    Emp selectByPrimaryKey(Short empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMP
     *
     * @mbg.generated Tue Sep 04 08:36:54 GMT+08:00 2018
     */
    int updateByPrimaryKey(Emp record);
}